### ISSUE TITLE
Invalid column name 'DTYPE' on MS SQL Database

### ISSUE THREAD

**Issue by sergeev-ms** [cuba-platform/emailtemplate-addon#20]
Got an error on opening Email Templates browse-screen while using MS SQL 2016
`SQLServerException: Invalid column name 'DTYPE'.`
<details>
 <summary>StackTrace</summary>
com.haulmont.cuba.core.global.RemoteException:
---
javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.3.2-cuba): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'DTYPE'.
Error Code: 207
Call: SELECT t1.ID, t1.DTYPE, t1.BCC, t1.CC, t1.CODE, t1.DELETE_TS, t1.DELETED_BY, t1.FROM_, t1.NAME, t1.SUBJECT, t1.TO_, t1.TYPE_, t1.USE_REPORT_SUBJECT, t1.VERSION, t1.GROUP_ID, t0.ID, t0.DELETE_TS, t0.DELETED_BY, t0.NAME, t0.VERSION FROM EMAILTEMPLATES_EMAIL_TEMPLATE t1 LEFT OUTER JOIN EMAILTEMPLATES_TEMPLATE_GROUP t0 ON (t0.ID = t1.GROUP_ID) WHERE (t1.DELETE_TS IS NULL)
Query: ReadAllQuery(referenceClass=EmailTemplate sql="SELECT t1.ID, t1.DTYPE, t1.BCC, t1.CC, t1.CODE, t1.DELETE_TS, t1.DELETED_BY, t1.FROM_, t1.NAME, t1.SUBJECT, t1.TO_, t1.TYPE_, t1.USE_REPORT_SUBJECT, t1.VERSION, t1.GROUP_ID, t0.ID, t0.DELETE_TS, t0.DELETED_BY, t0.NAME, t0.VERSION FROM EMAILTEMPLATES_EMAIL_TEMPLATE t1 LEFT OUTER JOIN EMAILTEMPLATES_TEMPLATE_GROUP t0 ON (t0.ID = t1.GROUP_ID) WHERE (t1.DELETE_TS IS NULL)")
FetchGroup(){cc, bcc, code, useReportSubject, subject, type, attachedTemplateReports => {class java.lang.Object=FetchGroup(attachedTemplateReports){deleteTs, updatedBy, createdBy, emailTemplate => {class java.lang.Object=FetchGroup(emailTemplate){cc, bcc, code, useReportSubject, subject, name, from, to, id, type, version}}, name, report => {class java.lang.Object=FetchGroup(report){reportType, deleteTs, localeNames, code, xml, defaultTemplate => {class java.lang.Object=FetchGroup(defaultTemplate){deleteTs, reportOutputType, id, version, deletedBy}}, name, description, id, version, deletedBy, group => {class java.lang.Object=FetchGroup(group){deleteTs, localeNames, id, title, version, deletedBy}}}}, createTs, id, updateTs, version, deletedBy, parameterValues => {class java.lang.Object=FetchGroup(parameterValues){deleteTs, parameterType, defaultValue, templateParameters => {class java.lang.Object=FetchGroup(templateParameters){name, id, version}}, alias, id, version, deletedBy}}}}, version, deletedBy, deleteTs, name, from, to, id, group => {class java.lang.Object=FetchGroup(group){deleteTs, name, id, version, deletedBy}}}
---
org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'DTYPE'.
Error Code: 207
Call: SELECT t1.ID, t1.DTYPE, t1.BCC, t1.CC, t1.CODE, t1.DELETE_TS, t1.DELETED_BY, t1.FROM_, t1.NAME, t1.SUBJECT, t1.TO_, t1.TYPE_, t1.USE_REPORT_SUBJECT, t1.VERSION, t1.GROUP_ID, t0.ID, t0.DELETE_TS, t0.DELETED_BY, t0.NAME, t0.VERSION FROM EMAILTEMPLATES_EMAIL_TEMPLATE t1 LEFT OUTER JOIN EMAILTEMPLATES_TEMPLATE_GROUP t0 ON (t0.ID = t1.GROUP_ID) WHERE (t1.DELETE_TS IS NULL)
Query: ReadAllQuery(referenceClass=EmailTemplate sql="SELECT t1.ID, t1.DTYPE, t1.BCC, t1.CC, t1.CODE, t1.DELETE_TS, t1.DELETED_BY, t1.FROM_, t1.NAME, t1.SUBJECT, t1.TO_, t1.TYPE_, t1.USE_REPORT_SUBJECT, t1.VERSION, t1.GROUP_ID, t0.ID, t0.DELETE_TS, t0.DELETED_BY, t0.NAME, t0.VERSION FROM EMAILTEMPLATES_EMAIL_TEMPLATE t1 LEFT OUTER JOIN EMAILTEMPLATES_TEMPLATE_GROUP t0 ON (t0.ID = t1.GROUP_ID) WHERE (t1.DELETE_TS IS NULL)")
FetchGroup(){cc, bcc, code, useReportSubject, subject, type, attachedTemplateReports => {class java.lang.Object=FetchGroup(attachedTemplateReports){deleteTs, updatedBy, createdBy, emailTemplate => {class java.lang.Object=FetchGroup(emailTemplate){cc, bcc, code, useReportSubject, subject, name, from, to, id, type, version}}, name, report => {class java.lang.Object=FetchGroup(report){reportType, deleteTs, localeNames, code, xml, defaultTemplate => {class java.lang.Object=FetchGroup(defaultTemplate){deleteTs, reportOutputType, id, version, deletedBy}}, name, description, id, version, deletedBy, group => {class java.lang.Object=FetchGroup(group){deleteTs, localeNames, id, title, version, deletedBy}}}}, createTs, id, updateTs, version, deletedBy, parameterValues => {class java.lang.Object=FetchGroup(parameterValues){deleteTs, parameterType, defaultValue, templateParameters => {class java.lang.Object=FetchGroup(templateParameters){name, id, version}}, alias, id, version, deletedBy}}}}, version, deletedBy, deleteTs, name, from, to, id, group => {class java.lang.Object=FetchGroup(group){deleteTs, name, id, version, deletedBy}}}
---
com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'DTYPE'.
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:129)
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy261.loadList(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.haulmont.cuba.core.sys.remoting.LocalServiceInvokerImpl.invoke(LocalServiceInvokerImpl.java:94)
	at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:154)
	at com.sun.proxy.$Proxy39.loadList(Unknown Source)
	at com.haulmont.cuba.client.sys.DataManagerClientImpl.loadList(DataManagerClientImpl.java:57)
	at com.haulmont.cuba.gui.data.impl.GenericDataSupplier.loadList(GenericDataSupplier.java:117)
	at com.haulmont.cuba.gui.data.impl.CollectionDatasourceImpl.loadData(CollectionDatasourceImpl.java:614)
	at com.haulmont.cuba.gui.data.impl.CollectionDatasourceImpl.refresh(CollectionDatasourceImpl.java:161)
	at com.haulmont.cuba.gui.data.impl.CollectionDatasourceImpl.refresh(CollectionDatasourceImpl.java:119)
	at com.haulmont.cuba.gui.data.impl.GroupDatasourceImpl.setSuspended(GroupDatasourceImpl.java:191)
	at com.haulmont.cuba.gui.data.impl.DsContextImpl.resumeSuspended(DsContextImpl.java:84)
	at com.haulmont.cuba.web.sys.WebScreens.afterShowWindow(WebScreens.java:575)
	at com.haulmont.cuba.web.sys.WebScreens.show(WebScreens.java:457)
	at com.haulmont.cuba.web.sys.WebScreens.showFromNavigation(WebScreens.java:527)
	at com.haulmont.cuba.gui.config.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:213)
	at com.haulmont.cuba.web.sys.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:264)
	at com.haulmont.cuba.web.sys.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:249)
	at com.haulmont.cuba.web.gui.components.mainwindow.WebSideMenu$MenuItemImpl.menuSelected(WebSideMenu.java:569)
	at com.haulmont.cuba.web.widgets.CubaSideMenu$1.menuItemTriggered(CubaSideMenu.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
	at jespa.http.HttpSecurityService.doFilter(HttpSecurityService.java:1596)
	at com.borets.wedb.web.JespaAuthProvider.doFilter(JespaAuthProvider.java:94)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:112)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
</details>

**Comment by zaharchenko-evgeny** [comment]
Hi @sergeev-ms 

We have recently released new addon version `1.0.3` for CUBA 6.10 and `1.1.3` for CUBA 7.0, these versions contain DB scripts for MS SQL and MySQL databases.

Regards,
Evgeny
