### ISSUE TITLE
Error in email template screen after create db with hsql db

### ISSUE THREAD

**Issue by alex-haulmont** [cuba-platform/emailtemplate-addon#34]
### Environment

- Platform version: 7.1.4
- Addon version: 1.3.0

- Client type: Web
- Browser: Chrome
- Database:  HSQL server
- Operating system:  macOS

### Description of the bug or enhancement

- createDb task on mostly clean project
- open email templates browse screen
- see exception

Edit: turns out it doesn't appear after just a db creation. I created a report, generated an insert script and after that, after createDb I can't open email template browse screen.

> `com.haulmont.cuba.core.global.RemoteException:
---
javax.persistence.PersistenceException: Exception [EclipseLink-44] (Eclipse Persistence Services - 2.7.3.6-cuba): org.eclipse.persistence.exceptions.DescriptorException
Exception Description: Missing class indicator field from database row [ArrayRecord(
	EMAILTEMPLATES_EMAIL_TEMPLATE.ID => ea4f420a-43a0-3b19-773c-d28f96ed4b5d
	EMAILTEMPLATES_EMAIL_TEMPLATE.DTYPE => null
	EMAILTEMPLATES_EMAIL_TEMPLATE.BCC => null
	EMAILTEMPLATES_EMAIL_TEMPLATE.CC => null
	EMAILTEMPLATES_EMAIL_TEMPLATE.CODE => confirmation
	EMAILTEMPLATES_EMAIL_TEMPLATE.DELETE_TS => null
	EMAILTEMPLATES_EMAIL_TEMPLATE.DELETED_BY => null
	EMAILTEMPLATES_EMAIL_TEMPLATE.FROM_ => null
	EMAILTEMPLATES_EMAIL_TEMPLATE.NAME => confirmation
	EMAILTEMPLATES_EMAIL_TEMPLATE.SUBJECT => Coral Project Registration Confirmation
	EMAILTEMPLATES_EMAIL_TEMPLATE.TO_ => null
	EMAILTEMPLATES_EMAIL_TEMPLATE.TYPE_ => json
	EMAILTEMPLATES_EMAIL_TEMPLATE.USE_REPORT_SUBJECT => true
	EMAILTEMPLATES_EMAIL_TEMPLATE.VERSION => 4
	EMAILTEMPLATES_EMAIL_TEMPLATE.GROUP_ID => null
	EMAILTEMPLATES_TEMPLATE_GROUP.ID => null
	EMAILTEMPLATES_TEMPLATE_GROUP.DELETE_TS => null
	EMAILTEMPLATES_TEMPLATE_GROUP.DELETED_BY => null
	EMAILTEMPLATES_TEMPLATE_GROUP.NAME => null
	EMAILTEMPLATES_TEMPLATE_GROUP.VERSION => null)].
Descriptor: RelationalDescriptor(com.haulmont.addon.emailtemplates.entity.EmailTemplate --> [DatabaseTable(EMAILTEMPLATES_EMAIL_TEMPLATE)])
---
org.eclipse.persistence.exceptions.DescriptorException: 
Exception Description: Missing class indicator field from database row [ArrayRecord(
	EMAILTEMPLATES_EMAIL_TEMPLATE.ID => ea4f420a-43a0-3b19-773c-d28f96ed4b5d
	EMAILTEMPLATES_EMAIL_TEMPLATE.DTYPE => null
	EMAILTEMPLATES_EMAIL_TEMPLATE.BCC => null
	EMAILTEMPLATES_EMAIL_TEMPLATE.CC => null
	EMAILTEMPLATES_EMAIL_TEMPLATE.CODE => confirmation
	EMAILTEMPLATES_EMAIL_TEMPLATE.DELETE_TS => null
	EMAILTEMPLATES_EMAIL_TEMPLATE.DELETED_BY => null
	EMAILTEMPLATES_EMAIL_TEMPLATE.FROM_ => null
	EMAILTEMPLATES_EMAIL_TEMPLATE.NAME => confirmation
	EMAILTEMPLATES_EMAIL_TEMPLATE.SUBJECT => Coral Project Registration Confirmation
	EMAILTEMPLATES_EMAIL_TEMPLATE.TO_ => null
	EMAILTEMPLATES_EMAIL_TEMPLATE.TYPE_ => json
	EMAILTEMPLATES_EMAIL_TEMPLATE.USE_REPORT_SUBJECT => true
	EMAILTEMPLATES_EMAIL_TEMPLATE.VERSION => 4
	EMAILTEMPLATES_EMAIL_TEMPLATE.GROUP_ID => null
	EMAILTEMPLATES_TEMPLATE_GROUP.ID => null
	EMAILTEMPLATES_TEMPLATE_GROUP.DELETE_TS => null
	EMAILTEMPLATES_TEMPLATE_GROUP.DELETED_BY => null
	EMAILTEMPLATES_TEMPLATE_GROUP.NAME => null
	EMAILTEMPLATES_TEMPLATE_GROUP.VERSION => null)].
Descriptor: RelationalDescriptor(com.haulmont.addon.emailtemplates.entity.EmailTemplate --> [DatabaseTable(EMAILTEMPLATES_EMAIL_TEMPLATE)])
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:124)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy218.loadList(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.haulmont.cuba.core.sys.remoting.LocalServiceInvokerImpl.invoke(LocalServiceInvokerImpl.java:94)
	at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:154)
	at com.sun.proxy.$Proxy34.loadList(Unknown Source)
	at com.haulmont.cuba.client.sys.DataManagerClientImpl.loadList(DataManagerClientImpl.java:57)
	at com.haulmont.cuba.gui.data.impl.GenericDataSupplier.loadList(GenericDataSupplier.java:117)
	at com.haulmont.cuba.gui.data.impl.CollectionDatasourceImpl.loadData(CollectionDatasourceImpl.java:624)
	at com.haulmont.cuba.gui.data.impl.CollectionDatasourceImpl.refresh(CollectionDatasourceImpl.java:165)
	at com.haulmont.cuba.gui.data.impl.CollectionDatasourceImpl.refresh(CollectionDatasourceImpl.java:123)
	at com.haulmont.cuba.gui.data.impl.GroupDatasourceImpl.setSuspended(GroupDatasourceImpl.java:191)
	at com.haulmont.cuba.gui.data.impl.DsContextImpl.resumeSuspended(DsContextImpl.java:84)
	at com.haulmont.cuba.web.sys.WebScreens.afterShowWindow(WebScreens.java:595)
	at com.haulmont.cuba.web.sys.WebScreens.show(WebScreens.java:471)
	at com.haulmont.cuba.web.sys.WebScreens.showFromNavigation(WebScreens.java:543)
	at com.haulmont.cuba.gui.config.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:335)
	at com.haulmont.cuba.web.sys.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:264)
	at com.haulmont.cuba.web.sys.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:249)
	at com.haulmont.cuba.web.gui.components.mainwindow.WebSideMenu$MenuItemImpl.menuSelected(WebSideMenu.java:573)
	at com.haulmont.cuba.web.widgets.CubaSideMenu$1.menuItemTriggered(CubaSideMenu.java:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:153)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:115)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:431)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1577)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1747)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by alex-haulmont** [comment]
The problem was in default cuba insert script generation. It doesn't add DTYPE column with value 'emailtemplates$JsonEmailTemplate' to the sql script.
